import{S as m,i as c}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();function f(o){const r="https://pixabay.com/api/",i="43587882-3fd012595c4df59010c013d1f",s=new URLSearchParams({key:i,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${r}?${s}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function h(o){return o.reduce((r,{webformatURL:i,largeImageURL:s,tags:e,likes:t,views:n,comments:d,downloads:p})=>r+=`
        <li class="gallery-item">
            <a class="gallery-link" href="${s}">
                <img class="gallery-img" src="${i}" alt="${e}" />
            </a>
            <div class="gallery-block">
                <p class="gallery-block__description"><span>likes</span>${t}</p>
                <p class="gallery-block__description"><span>views</span>${n}</p>
                <p class="gallery-block__description"><span>comments</span> ${d}</p>
                <p class="gallery-block__description"><span>downloads</span>${p}</p>
            </div>
        </li>
        `,"")}let y=new m(".gallery a",{sourceAttr:"href",captionsData:"alt",captionPosition:"bottom",captionDelay:250});const u=document.querySelector(".js__search-form"),l=document.querySelector(".js__list"),a=document.querySelector(".loader");u.addEventListener("submit",g);function g(o){o.preventDefault();const{picture:r}=o.currentTarget.elements,i=r.value.trim();if(a.classList.remove("hide"),l.innerHTML="",!i){c.error({title:"Error",message:"Please enter details"}),a.classList.add("hide");return}f(r.value).then(s=>{s.hits.length?setTimeout(()=>{l.insertAdjacentHTML("beforeend",h(s.hits)),y.refresh()},1e3):c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",transitionIn:"bounceInUp",messageColor:"white",timeout:5e3})}).catch(s=>{c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",transitionIn:"bounceInUp",messageColor:"white",timeout:2e3}),a.classList.add("hide")}).finally(()=>{a.classList.add("hide"),u.reset()})}
//# sourceMappingURL=commonHelpers.js.map
